services:
  db:
    image: postgres:16-alpine
    container_name: todo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_dev
    ports:
      - "5432:5432"
