FROM node:18-alpine

WORKDIR /app

# 依存ファイルだけ先にコピー
COPY package*.json ./
COPY prisma ./prisma          # ← 行を分けると安全

RUN npm ci --omit=dev         # 本番依存のみインストール
RUN npx prisma generate       # Client 生成

# 残りのソース
COPY . .

# Render が自動で渡す $PORT をそのまま使う
ENV PORT 10000

# 起動時にマイグレーション → アプリ起動
CMD ["sh","-c","npx prisma migrate deploy && node index.js"]
