FROM node:18-alpine

WORKDIR /app

# 依存ファイルだけコピー
COPY package*.json ./
COPY prisma ./prisma

RUN npm ci --omit=dev
RUN npx prisma generate

# 残りのソース
COPY . .

ENV PORT 10000           # Render が注入する PORT を受け取る

CMD ["sh", "-c", "npx prisma migrate deploy && node index.js"]
