### 1. Health-check
GET {{HOST}}/healt

### 2. 全件取得
GET {{HOST}}/todos
h
### 3. 追加
POST {{HOST}}/todos
Content-Type: application/json

{
  "text": "課題をやる"
}

### 4. 更新
PUT {{HOST}}/todos/1
Content-Type: application/json

{
  "text": "課題を終わらせる"
}

### 5. 削除
DELETE {{HOST}}/todos/1
